#!/bin/bash

# Bulk install VSCode extensions
# Currently this installs extensions to VSCode Insiders Edition from VSCode

GREEN='\033[0;32m'
BLUE='\033[0;34m'
NO_COLOR='\033[0m'

# Or replace exts with an array of your own extensions
exts=$(code --list-extensions)
count=$(echo $exts | tr " " "\n" | wc -l | tr -d '[:space:]')

echo -e "\nPreparing to install the following VSCode Extensions ($count):\n"

for ext in $exts; do
        echo -e "${BLUE}Installing:${GREEN} $ext"
        code-insiders --install-extension $ext
        echo "" # new line exec above
done
